export const letftRowSeats = [
  {
    id: '#001',
    selected: false,
    isBooked: true,
    seatNumber: "L1",
  },
  {
    id: '#002',
    selected: false,
    isBooked: false,
    seatNumber: "L2",
  },
  {
    id: '#003',
    selected: false,
    isBooked: false,
    seatNumber: "L3",
  },
  {
    id: '#004',
    selected: false,
    isBooked: false,
    seatNumber: "L4",
  },
  {
    id: '#005',
    selected: false,
    isBooked: false,
    seatNumber: "L5",
  },
  {
    id: '#006',
    selected: false,
    isBooked: false,
    seatNumber: "L6",
  },
  {
    id: '#007',
    selected: false,
    isBooked: false,
    seatNumber: "L7",
  },
  {
    id: '#008',
    selected: false,
    isBooked: false,
    seatNumber: "L8",
  },
  {
    id: '#009',
    selected: false,
    isBooked: false,
    seatNumber: "L9",
  },
  {
    id: '#010',
    selected: false,
    isBooked: false,
    seatNumber: "L10",
  },
  {
    id: '#011',
    selected: false,
    isBooked: false,
    seatNumber: "L11",
  },
  {
    id: '#012',
    selected: false,
    isBooked: false,
    seatNumber: "L12",
  },
  {
    id: '#013',
    selected: false,
    isBooked: false,
    seatNumber: "L13",
  },
  {
    id: '#014',
    selected: false,
    isBooked: true,
    seatNumber: "L14",
  },
  {
    id: '#015',
    selected: false,
    isBooked: false,
    seatNumber: "L15",
  },
  {
    id: '#016',
    selected: false,
    isBooked: true,
    seatNumber: "L16",
  },
];

export const rightRowSeats = [
  {
    id: '#001',
    selected: false,
    isBooked: false,
    seatNumber: "R1",
  },
  {
    id: '#002',
    selected: false,
    isBooked: false,
    seatNumber: "R2",
  },
  {
    id: '#003',
    selected: false,
    isBooked: false,
    seatNumber: "R3",
  },
  {
    id: '#004',
    selected: false,
    isBooked: false,
    seatNumber: "R4",
  },
  {
    id: '#005',
    selected: false,
    isBooked: true,
    seatNumber: "R5",
  },
  {
    id: '#006',
    selected: false,
    isBooked: false,
    seatNumber: "R6",
  },
  {
    id: '#007',
    selected: false,
    isBooked: false,
    seatNumber: "R7",
  },
  {
    id: '#008',
    selected: false,
    isBooked: false,
    seatNumber: "R8",
  },
  {
    id: '#009',
    selected: false,
    isBooked: false,
    seatNumber: "R9",
  },
  {
    id: '#010',
    selected: false,
    isBooked: false,
    seatNumber: "R10",
  },
  {
    id: '#011',
    selected: false,
    isBooked: true,
    seatNumber: "R11",
  },
  {
    id: '#012',
    selected: false,
    isBooked: false,
    seatNumber: "R12",
  },
  {
    id: '#013',
    selected: false,
    isBooked: false,
    seatNumber: "R13",
  },
  {
    id: '#014',
    selected: false,
    isBooked: false,
    seatNumber: "R14",
  },
  {
    id: '#015',
    selected: false,
    isBooked: false,
    seatNumber: "R15",
  },
  {
    id: '#016',
    selected: false,
    isBooked: false,
    seatNumber: "R6",
  },
  {
    id: '#017',
    selected: false,
    isBooked: false,
    seatNumber: "R17",
  },
  {
    id: '#018',
    selected: false,
    isBooked: false,
    seatNumber: "R18",
  },
  {
    id: '#019',
    selected: false,
    isBooked: false,
    seatNumber: "R19",
  },
  {
    id: '#020',
    selected: false,
    isBooked: false,
    seatNumber: "R20",
  },
  {
    id: '#021',
    selected: false,
    isBooked: false,
    seatNumber: "R21",
  },
  {
    id: '#022',
    selected: false,
    isBooked: false,
    seatNumber: "R22",
  },
  {
    id: '#023',
    selected: false,
    isBooked: true,
    seatNumber: "R23",
  },
  {
    id: '#024',
    selected: false,
    isBooked: false,
    seatNumber: "R24",
  },
];
